---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: audit
    image: node:12
    commands:
      - npm audit --package-lock-only --audit-level=moderate

  - name: install
    image: node:12
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true

  #- name: test
  #  image: node:12
  #  commands:
  #    - npm test

  #- name: check-coverage
  #  image: node:12
  #  commands:
  #    - npm run check-coverage

  - name: build
    image: node:12
    commands:
      - npm run build
      - NPM_CONFIG_IGNORE_SCRIPTS=true npm ci --production

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: docker 
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/melinda-record-dump-exporter
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: docker_username
data: cn2kl5OrGYI3bXz6tPFelCzpAaWJ9HThqee80QFQuJGPKxyK6K7yXtzNgFmRGsMELgo=
---
kind: secret
name: docker_password
data: MTHebAfxi3XiTR4XGKz1QS8j9zJHNtDou22Jl/WSduikn/r/eU5bC49dPgYIsfqvRX8Oz86L0klp67uJNIwa1Fo1jukePea8ndPUSQQkVOeve+6wIErJGZE0goA=
---
kind: secret
name: ssh_key
data: ljSJ89UKTzjbfrvE/mmHbXApYhYQtpZVaa7B/HqAwpRAmLahT2myQjabS4/VQjX/IOdQk2Yz8EPftZhL/N5y23sgzvEsUEkiRhd0P3jLPA4pBbPzcNO972gdyPMdytn7md46i+GnsGzfkcYFJcKf6pa9qAoowNEHlGYVUeriUMPOzJtDVNLgiSKMCVL2CZjMZUNjzM3L/qxAUDLJ4s2xWA0fWdWNcXlX3TqbdiOggdGd+qXUGPRhSfdbO2m7hcG8aHE3hbkfkijO/H81xYOvj3nDFDZExVDI+iEaefgMVya6T7qm8FZijmA34NNvz7LD2XNjYa9BeN9OFBNqh/fDbuw6VVpUlTVRmgkXtsFe2Lw3KPLg2Ou+ssyjwyFTkYoTR7oAwYMi904tzNGU5Q+gI5r7pvdFjefefgFszOljhBuCAE9BiW1A21X0AUPlK93JZX6Ufbdf9fHfF4u2uvpHFCeYzl/lWhKqYrCetGLZqGrSpIfAkwk0k+uNRdHxJ+javjavCmoa43ktF/7IoT5ankpIIEQi+aRCaJi1eb1v1EKvXO4l8vcja56KCSkRh4wqLM+92+lsG4lC8gWKHXX2l/s479JiSXIg0n4xwuDTYe2jdISFu+s1RrgIz1dB/TrHlT/+bAYlV3EWVK20oD2gFXkzFpjsRJZ4PVFLl5+CFKQIMhe/36eX7zELDDynuN/UL3WvavyQWpSua4r6zmiVQh8d5YqaEn/kQpECny02jToZVqmiinEPclfcJV1ySD4Twer4PFIbYjX2e1MrWKKdskkzuw08sSOeWzGPauZj1h0EKugnjTqP0eIV+O4jTcueQrBSAgkuPqKDOcVxoEAkNlgBVkwvepqtO0FMjr+0EoJjq8H3bRk/CUIpPX+0oOb9n3BHn08P/tGfn3jIITg7eZ7AvNMWxFlD/EmFaeMvCQ5jWD1i4LuOGKDQ648I+ynQKAFqdH7eN9ZTNhmm6dgcQX5or71OWW6sUqoHkmusbBV1zqwQD7qNoa2RaVfYOpFlLvDlQHIKsS+XlPTsnZ0Rzok3OWizgc0IikEa9RUJYOsxCIZ8tM6WyOkYR4p7Dz5UUZrgQVJPhhu/YyymOOJZ9t0T1yDndm7bCwGlj6yPkV5JbQKyP752J7Sia2CdNUNOLC7/BIbaD9PBy1t/IPOGkzHx1ngDyckORQ4Dgs0r72OUNXeIGSAo4XyT/K1J8BLuxctlTjC79kiuHCMQa7Frd/QqnK69SkxziCRI0oxCY8Czub3upRIjAlGGvDHE2/dnv3Nmf4kR10DKnDl8RyeLy5vrh07Nx/1hTbQGyq4MKaPgGVhY+4sT+KMLYakmcGnvsR3cn8GISCQNyaLMZLmXupfZXfyqdtNfLcIfY0087KPOMBfjgmd53Dc74FVPpFxhYilIQ8ElVsHE1aoWqc4jv3FzajPwPujH9QMIQ9FBkGan8YFntBOCB6UHI8SAtvkYF4NchfmLXWBGalywe5pxomW38rbUVnnf4iLU+DWjkQs+D/iBuKlPWxE+3qjoejIl5PYj6CGqXIq2bHjiCMa6JoWqOTJYrmk0mwOyxyA/2XP2KFMu3ugL9ozvoacnDyFuzh66L72YMfljEpXD3+GFsePyA0njmaOrwhKr0voGpJfP14mHJeyqO/r4SFYYyb8GfmxgVGYDi9VTEdmgZcwXKjdAQmsAcCG+SOxEVIoBWmURLDM+PTBjXH8SrH6hCWkXW/fUPYYWuQ1cXui63tKvpN32R8gDimRMnZMUceCyf65O0RZlBjXL0WCcv1jN1eloUUS2Y3raELmw29O02MBCdpeP4NuPs4hcmRBK3CMPzi1iOLmOdQ7ETn6Frd9MT0OCm0IYwxT3Ks52Y/zhHtzrEXZbaA7sMmyDkBeRrCdFJ0671G3vL7OXaQfXyQsH98+6ifFhCFrEfpGQESqLbNAhekcp5F08H0AlSVgEnKgluX2+MdxnTkhtNv4d6c3Gk8VnYY7dPyJ2Tdz5t5ekL7cIScrc8Pfe1OVdjM0anCfVarvAdG4oA2ovKKVDer9i6TwyFB3oewG7Yny0JsM0Mv/e/Ye7yMBo+hXciFBhMi3R4ao3Qi+i25qiIX4qxA5YlKQ7F18xfAxCU0PjJve5uxaJhNUxfOuiiC3WeUO257C2G6po0jGAOBr0wfonmky0pPuPKayJqocR6tyyjqbXQXjxw089J/Mm3c6dKx4QuTJgUlspSigkjPmgBn08eRpBZyTaOQEE4z/nZ7u71hECjIyTKPCnBp97bRI2mTp5pawoAZtkhCFNR5DaD7dBnvJzmTUkP7Mqa/YL0saw74ZhhrsTZ2g/0kZWMAa69XeL1F8ZkyUDS3OLcuTKRuTUaNdDLDagvmGv8M6Ax01w12N1Tu23EQSRo3u7CrldkN3qkCKQ9oduObzTvxk7TYEM8DlTMSsP0MDKMfRNZMAYe+/CCYdXYHQTGYHXieHhq0/gcaYWSo1SApcUrqODXbuRxEraesEQ8b2VfrFpNKt/k9OJNZDF/kSlGZO6RPH+FRjLLX29/5agtrBOlWX3LHk8W1Gd+jfYr37XpGLgDZlb1WGw7paAOHGoNe7tBg7r2jOR8hhjWDR+QIf+2lXUEFnC15LshWZcDitfI/MFsyyZkXNrP3jTfbXbll7/eitjlMUL1iO5TStZEFM+p2MRjkxxKZT86XeVia2AAyr+FK3NPcZ6OmR8FYqlC+pWTwurqc8ghl0jzZgTXpWSuU2YwO7vS6YmQBs2FAHgxfUfs4IjDrlhbnO5Ri8XphF5N5VXlEEYBjrly7sykjuRKOuLjcp4c6wDrGpeVYpWxea3N7VA4QAdVi+WzyNJluXFv/DMI70NnKXVl5/mACgYcNpVjczD5b10f11wpMGOBK7Va58B3mkHKkypgZLrmJRyqPTPSPw+2iSaJxyfV6VRY5LIeASGnBwdXItNc96CnOZl+ila2rH970ei/R1KEyWFzFXF/6m0eRzfgBGf674LRWH2HUbpDLQMf7XtdowB92GcGGocnNCV
---
kind: secret
name: gpg_key
data: 2yh0n+Bmxvew3sAgqASnqPmVFEkGk1ky3/i4+olyeTOaoOvdNjUUiabwkHtr4JPKv7T+WLx71JdZzqREkcnjea+l90HKbLnLSj1FGYueMwgiiZxwDAbl5ggt3G5zLcPHid9KUPrKPsevXL0nK+NZQ8ZQ5UEGsX5nGci/NPUM9vrwHAbwPbmkaV2iqg0ooK5psSW7RZ8ipstTCpL9WBdIHkQ5FqOx0w9fv5QAp68NwZHcvR+vg7/kVZX0cHPaAXG8lJCGPkF0Ac6vTIaZ/Ph2jX28q0GHmkkCAvuyCJVdTad6MSBEnZLLbblqJshuewgiN6u7VPsTiLoM382YMQrMM6ak3op30eRIyvOjgJ+AxTTRNE7Ieqp3HiZU5YbajXdysH5IMx7cco00cY0yGL6SLNN2OFP8YuTZ4SsTmUXhYizOJLCnQMgOh/iiFxat/7Oqw2FTytF7bsTaRRm6vBQZ9m7qA6XMQLTeubTYgHlZ1EVKT8qlVL6NGYoHGz7ylMG5lm4B054pTnFCe7mGcURuA+7X6+dcOEDA7Jjk5tiVO8SvsZ3PrgMOCB+hHp6iiDlZruu2b9BHbILc9x0+plpUfH7yBVj2aB2CBdXK+m6uIlReJofShaqH7QSQoti7zEqNZGgIJPKyLAoPGG5oOE4ZVVTnb1HcbEkRlx7Dwbs2eULmtj/pI94hJERcEVTHxriM4hwwChY75dfNQR5KjigTb/r9pMqaBAyOvHmi0daW1IINrhy56cE9g2GxcNfjUXdlsNUhFpxVXRvCwvVMF/kO5p1mXG8SIS/qld8srYj2tCZG1oDkXJsZmCXkPbMSPQ515IO6eMzjOoKWsUlB1SFMt2Cn0KXws4FI67hS/H/iYqAhlGMSt6CxsVbKz3uzbLawaGFedvtfYZyzL5u0G3GKSGcwPVsJ/9meQzxQz+pRlJkoawBEGfX4cgcZtqnIy5Mt3FXDYni+ZCx4xiKIQMFpBPD3ZtntQIaHqvFm0KHnE3x3SBc0swSog+p/rfm3Y7J08k0o8NrOs5ho27yivkICx/Ttj8VmnrqCADop+vMiTUb1Ltx2cqsZ9dnmbBdL248xFUb/BkjzpSktxzs3Zu80v8SZ/ZNMscSKW7ffN75vBP0iAcvMYnMfdseLgI8xeOtOogAdhD5Mt59EGSoe/XUiJzgon6lv5N1G97HmNmYBbB0rswVeci4zBZdAHqRsiWKYzJZ65cFluD/PKpcA6HCSiK9Wx61KVpo74Yh4yZps2UR9N93C7nMZ8Qg5oeXKvYofGMAFIG+Sbsg9PHOkR6QJwnJyxquju8J73gaAl2heek84Nm96mO0gONQmMWKGgLekCRHj8jKpGyLUyWgSKvz1xLzvxBEBSniGfcK0/ZI3oQ+dUc2Xe3lSoX5a7ToWYlSxpBpzH4Yv1yHzXBRRIs8/uvNiYK0tTv8V2spjQyQ/SvFCrAvEny4EbjEFHBdnoMFtmfVLsYeuRxGNyNyQ5agvDpUMWrZMEq9+O/4U+y83Dcvc2GQJk/t8rnAPmwcrryp+iL8BfVFC5qb4tvwWJepL0Us0plo5nFuX0WYYY3b80f11YSul8Dd5+C6/oQjbkVhFd24EKqvmrKth8k47GtdzTzcSjokjv6N5QYz6wEeihO70TCLFVRG1AC0tZVEcRjPNnVZbKRMLRE9ZRDTA4BGWqdz+XRii8sF2Go44NotVbDbgkW49DUjRiinnuRxJYnPTCh6jfbG08HBBEUQ76IaL2Et61MqutVf1EMCnPQs2viEaBlKwjmro8skgPkJfWWxlHWF8SR4nJe8XWUTS8D2HFluPReIFabK3I53y75NTvDLbgsrSj2YlXL3vVcP8XF7KeHiZNVZzstVOvmrhRTn5R3R6QU2dwlD9EzTSyW0EnP1o933kBlNqi2oUGoDLANGqph0XzDUSWD+Ve4L6soW9yZMkBEzC6/eOiOKOJ2dOjzF4TzO/5W3ARMcyfzCTX+jblYCuFFJg7ztiPS5M94GqOZtXJVIHZWCnxSiZc6nk6IfveocctLTwwHoHkTnn2+qv2Q7rsQhSh5yyGlpIdfVr/6nRl/iFD8EJr5sDMbxSnAzRchdv0EYTSzkT3f9D8TsnOPNM4N+2HrVcr6lwYq1XlSDucxyzSRvdrEYpniHMv8vd1jZKoLwQ2h3D9ggO4XMxdxJYv7FbahFmFyORwvQEO+TMNgOVd/g0S9oPnRpzRD7GqXLXnAKoRKQfrNO4s9SnOrITZtQbadXKXZeYQUQV5qtUdCJZgFfMaJwX/P/nTAWi24IifZJkOzh/9CirlFJb/Q+DWSXn/Leqko70mF4V5rVDVwUDPPqRHxHp1x76ZgAB5169JJK62CLBhQDWq4W/SVY/wBlb6h+NVFtMrqsTZSneWhTCQXGsSdtM/qBD2TlwXkvD/8USragB/zsE0wfJ5MlM1YLkvXoCCgL9zIOdQ5N6NSRJt2kZvCB6F6hh4btZYW6sxHSxFGkGgYFvjcdVuVjqwnJe8JSy2FQLGh2s9hUMtQsydTF+4XrktkbsGJG/EjuaOlMyik63ncyT8CZEVqFcFLI0Q6kKPIamnPlEsZwMsi74DpwkclPoYypePFsS7ZzrPp2H6WI7yXhjmU352Yg6u7rUu8l3H5mcx6UI6UpbSnczixtfukCbSY+1Nix0XLx+jPmDn3sf2uCJoUx7HpkBx7u2uIzLnz5M8qFcpSciSIXqh+qL1C895h/DG3lBsUkwa70n67RM2pt8uTpGkAwJikXbBuEAAv40Hi2T6G58DdeHbZwCTxlYJoWf9xmfcfBovOv5XhlrGYjQKLmfB+d9ZBqVqXKXO6hTGbYRmFROj47P8xjfRZYW0C3R056riCWPeIsv8glfX7uO8z3NOOhq+OMD2815kzf29zUbADUA+vAq88hfBPWeqdytG1CFt2KFtE8bGjUPUtIwGONrxTxSfBsBjOGxMMRAwskIA8TL9UKgzpMX2PexeczY1WHs3E+EOHh37Hxp5oPfjf/jTEZkpH9vhL29PHzu/UIeQ/kZa9ZKCwr+EAdZqG2+CU9vBTEttP0EX76XgBfx+47ska80uF1pg4qnTjAj3QtGI4iEKsRU/hZqz2YfycjaKfD1OiSbU0OedUGKP/BY4qI28+UrjIgbOwbox7piCjz/28ddY7LBgVCCbMxqjnk298nxUGOJJ4eSUjkHGqd8Y6VkI+UEBUyQVxAKgUMeL8hC9VhafUMbtreYoRZddicLK2GByDS/AxXFuEDzSEiNtd1qX10ZOSlfzJm7POp8BTtrR/aOiW10iGVCe0tdpubqM+neOxVBiAi5l5XPm56JL1TKVW7dTlEQE2LPHpovMb4mjxYAIXhbW2tJmX65Al662sya6Skoz0qZORbB8OaEwhOP6jfXobYU+nLFvXFJTOE6JA5BR7nlG2FZrQsXCTZNQrJIpip/JhKhqcco6OLBVOcCao84Ohviuz1vM/IYYL+38MTablnL3wpSID4gQLAb0ACKUGE07iZ80dxi3SaPCpui5pYWQE30lR6sCVUKTlRAAP2HP19HgW2LCQFTGYe/RUM9OA70J2eBJyW4e12KBVLOaYjOU6Uqez7KBKX4CkRR7+dq84EGWaFx4AG+r4RFj5mJ8OMM0uZxS4TISRPf7PEnQtW8GCvyxUKPo6R2rb8kPe1rrFUDOGJSs23YDmbriqHBGYS+jn/v9sMS28zEa9OTEb5PC06EGu/lft6t91hzRLWkI0FppW1Gzlc3Qs94Szdo2V+o1kMEP68cyrZHKhTSCj7Ykk+9w+N6wrZjN0qR2nrQ4ekPy3sOiPeY64c/NSktdZsFCIXelF+N8QHNNg4XdUQKlqcsI53SVK5+zBnLnXrSOxrARq89CIwGRDnlhnYG84VSlq32/+/0TwvrCS/nELVXJ2rskgXcRFtXIlKv08KukAa4cjP7nEwfM/5NxW7o4JRHb6SVbszdLB+/Gvz6Yo23YSkB52gCsSep6K4wzhjBtYsolcSW7tvComZy5m6moOHj7H5gJAYAcIaY5sofBdw6h18S3urXeRtSDFlYRVk3V/XDuk1tG6pHpXe3k7eGzaSTpLAjJt610ZrDSePZabKgPEDy/5+9xnmcGZpPLY+1T5pXfcD7KYfRt8vy96CRKWwoyrdGVQch13yPOHKTekEII2QMfZvN2/48hRoh1nkTK54RcUqheJ94yq2aCvQA7p/l0eayctbt5afn1k1iszYX9/kcQP2/qCvifsZn2bvLTGYJfUAIUtbquy1sFseUxpaCrxezqZ012i1/EoLJ5PsqSzXf1VcdCZ/qp1R/qvX/jB8MlC09cIaMCGuOEipbG6ebK4G+wEWDFi+g2CvpHbq1bTudOnn7acnHvRMiDafKRuX9vfOPGV6A3y47dF+TBzxs7oW6btkGAAS5rlro/Ai3o0jOtkmzSvrFPfsHDBkW7bVIrIZCb3bUXpOxjYDisLwesbIFKumryoMYk/hnn5ItNZj386239Dhiu2GkN9F+cHqhXP2ACba1eW5TjTYYk1/xrBCs1lLoKrqeJ9baR+gYtj1lSzNfp6n38iU2w0IbjjZJlcKVYFKuig6+7mMXKVnqDqUVrKR/uVDTYcr8zrVZK/Gho6PZI/iN91AnbPODj5eDYil6KLK18ctasoAUDHNf/t5jTuE+chDVOCFTskBB7mGoADh2UPB5QlrsXO1ApLYM8ULDNmhlcpknuwR3k3qJv19kFFXly8Auuilz7usxzcThfgMI01OhV8Z2MMhF6qy4lxegJyEozWQj2C5cfseceMqWNw1BBBwJVMeZKa31sy8WeF33J0MMDPKRpPkNeZEUfZyAqyUgAdTXYZsGI6YRQGvO9t91CYyLmofQr9q+IdK0iZxKBXp8pU1SZ1E+ydekfz1Vm42aCUp2lwrKxWl3fo7rNWODsEBboykfzPzKH8QJoK1zbTNJJ0kbXWU6CcM6lKUnOxuWP7jjcsJ3x94sPM6wgU7HwwtBMiu0G7jftsvPiQoFe48b2fGL0TIM7iZs3XjvwsoExqgCoNb0tByN/6Efx1znHRxsPxDmTTW4nFNI8LxNSGshe7ShXDPzV6cm2Z9o0x4vEunEfEe54e3y0mB6uiqeWSuqy2ITgun8tKCUG2DInTrG7IXMvtmhNEAHMmEbpS1kCCuH7/jYVqgcbEhqsXcPxyWNIqhbkH4aBCSY9j4kycejE2UiQipc7syH8S9LQdhaYdbfAAt+/66zpQo5ZfN+UAEtBRNaqivFdSjweciTsslyNbsiwQcXbDUGgMwhMAk4SvVfc6F96MKYlgbFsM85QgfzTyGRwnLEs0X7K7dASk1mcz2mR8C9R6mNWCZUhdz+lb3Z31Zc16UHATYJqflNL3qTw71BB3+d+T7XOfS8rPcd7N4dgyw9r4yH5JoiLMTY6zKRugl9FagoGgho2m5/xMEqZZ57MolPOKpqiaBh5/DAjVmUPI5q1HW9JcRKpF0sdfS5SlN1o4ablJAoyg8F67oZGDQ/ucB6lKNorNH0oIh0aLBG/2YOk7qFrFSEYmrq1CVfok1mWTIKstpAPc4jbZmQcJaae3fOhwfCuAStJwNPEZ3vd+mACYNbsT60Ejc6gOjR53nS7xXymM3Si9kudHeumNNnMe8tPQC8Wqi9OSY962KPq4ILJwz88cX3OaWamPEytewCgyq2shrVba1EFQ7wW7a/qSv/JGGXHZl0AjPTQaUTqUd84oc4FlmsLoWti1NW0H3cewky6CMfnKox7DGec4TjEAKAOTbmTpWdWBEfGu1txuLSvL++JrIvDM9lG4bdWNCukDfYBnsg2lj7u3pm2wN/eUDUvBrSkeL+l+YsidyKYNKtuqDxF9i7lutVUs0EMpjIBYX8/uce0Th80EJZECtb8HnzRTaKPhiWq95W+lrWIFFNIDt24b2BBs2pvszBvazV884Y3HTEVpy4Soj6MDBFa/d+nwxF48vFy6/efkykt8S2taJoisBoxiqSxcEkLZajzL/CZzN7tmEtt2gyvk++Q5BjZAQR4towVnRq+ZhXpmBatnyaIvdTcVM4S2yCJQZ2rHQUIklDkE/QlME3knl9yf4Q0vNabQvd0nQuuu9NjYBGv7ia9FHryOiz6pZoviM/Wg/z6YxlFgFtUBiAdyO+/ntirwuErO+oqb4QNskqc1tdrHC4gbEv9sq2VbTBZrqHZDdg0uJ1i+vpS60GnsXbBdYh7Cu85NvDKMLGigZ5IZvJ+yBrogrJvHJNCUmamJ3CeDdNxg6HF3n6sdu38pKgL7FDUswzobhGzAx4+r/14Rk/BCoesMmkTIp1o18YsCY7KQUp1AqU3xU6yZPy46JsTExuels8EafxjvPOiwl8VtoCdMRzQVffUOcZlmYpTLd4NcuQVIGRd69ckSDhS8KIum8GulPsZUAvIQ4oqJXF/LQvHjZcXBVLs3ykXDpABKor4Wa51/QwZwsJzfaM7+ykRSM4FP+48bHmlIyvtkA3lohludzsb+3og8RNYAdbMDRHESYJwU0dWVmb0fUJ3Y5Xokn4Kv8AyJ8qIDGpNjbCXzgVDVEf3Q9pBKdp1xPCvlBia1JC7r5VzmTYiN91GaqEhgaJBxANNXofUOPy0FV/uB+cVObyQ64kkHLjBX9GivHPEjTHcfECDqY44JbXl5U1Nhp/G7aPUrX7UQcPoNx4e5odcvUg7COWorXrW5hL1HVFWxhYR46IUg==
---
---
kind: signature
hmac: 66e5994ba870efaa010652ae548cdf5f727de49b923a9657acd744c8fd9eb799

...
